"""Add market price history

Revision ID: 04dcfec269cc
Revises: ea656fa50d48
Create Date: 2026-09-24 23:03:44.350622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04dcfec269cc'
down_revision: Union[str, Sequence[str], None] = 'ea656fa50d48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('high', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('low', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('close', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('adjusted_close', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['financial_instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price_history')
    # ### end Alembic commands ###
