"""Add price history uniqueness constraint

Revision ID: 274a37b29df0
Revises: 04dcfec269cc
Create Date: 2026-09-24 23:11:54.843158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '274a37b29df0'
down_revision: Union[str, Sequence[str], None] = '04dcfec269cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_price_history_instrument_date_source', 'price_history', ['instrument_id', 'price_date', 'source'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_price_history_instrument_date_source', 'price_history', type_='unique')
    # ### end Alembic commands ###
